export default {
    WIDTH: 600,
    HEIGHT: 800,
    WORKER_FOOD_DEC: 8,
    WORKER_ENERGY_DEC: 4,
    TICK_IN_DAY: 3000,
    MANAGER_SPEED: 220,
    COFFEE_VALUE: 70,
    ENERGY_DRINK_VALUE: 50,
    HAMBURGER_VALUE: 70
};
